name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Flutter Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Increase Gradle Memory
        run: |
          echo "org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" >> flutter_app/android/gradle.properties

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        working-directory: flutter_app
        run: flutter pub get

      - name: Build Release APK
        working-directory: flutter_app
        run: flutter build apk --debug --android-skip-build-dependency-validation
        env:
          GRADLE_OPTS: -Xmx4g

      - name: Upload Built APK
        uses: actions/upload-artifact@v4
        with:
          name: dental-clinic-debug-apk
          path: |
            flutter_app/build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: warn
